### ISSUE TITLE
Site crash after installing the plugin. 

### ISSUE THREAD

**Issue by limsocheat** [WP-Plus/Smart-Slider-3-REST-API#5]
Not working on the latest version of WordPress.

**Comment by zoliszabo** [comment]
Hi @limsocheat, 

Unfortunately this library is not compatible with Smart Slider 3.4 (and newer), which is most probably the cause of the issues in your case. Version 3.4 was a rather big rewrite of SS3, I did not have to use it anymore, hence this library was not brought up-to-date.
